### ISSUE TITLE
Add hover animations and link to respective section in "Explore Categories" section in home page

### ISSUE THREAD

**Issue by Dibyendu303** [rohan9024/ecommerce#42] opened 2022-12-10 19:20 UTC
When we hover on any category it should show animations and on clicking it should redirect to respective pages like Men, Women, Kids etc. 
![Screenshot (1924)](https://user-images.githubusercontent.com/66685553/206871816-16efcd38-b9ca-478a-a16b-0f04fe830a32.png)

Please assign me this task. @rohan9024

**Comment by rohan9024** [comment] 2022-12-11 07:28
@Dibyendu303 go for it

**Comment by Rishav1707** [comment] 2022-12-11 08:18
I have gone through this issue and also solve this but the problem is whenever the link refers to the required section, the page start from the bottom.
I have to start from the top...
How to resolve this...?? @rohan9024 
Any suggestion??

**Comment by Dibyendu303** [comment] 2022-12-11 08:29
@Rishav1707 I am currently working on it. I will fix this.

**Comment by Rishav1707** [comment] 2022-12-11 08:42
See the issue below:-


https://user-images.githubusercontent.com/97666287/206894293-aaf840f0-0225-4eec-9a9a-28437754091e.mp4

**Comment by rohan9024** [comment] 2022-12-11 08:44
@Rishav1707 okayy then raise a different issue and try solving it ....lemme know if you need any help

**Comment by Rishav1707** [comment] 2022-12-11 08:50
I only want to know how to use the scroll-to-top function on any section page. @rohan9024

**Comment by rohan9024** [comment] 2022-12-11 14:36
@Rishav1707 scroll to top is already implemented on homepage

**Comment by rohan9024** [comment] 2022-12-11 14:37
Closing this issue

**Closed by rohan9024** 2022-12-11 14:37 UTC
